FROM file_server_dev-base_modules AS base

FROM node:20-alpine AS ts-compiler
WORKDIR /usr/index
COPY ../../package.json ../../pnpm-lock.yaml ../../pnpm-workspace.yaml ../../tsconfig.json ./
COPY ../../apps ./apps
COPY ../../libs ./libs
COPY --from=base /usr/index/node_modules ./node_modules
RUN corepack enable && pnpm --filter @file/resize build

FROM keymetrics/pm2:18-alpine
WORKDIR /usr/index
ENV TZ=Asia/Seoul
ENV HOST=0.0.0.0
COPY --from=ts-compiler /usr/index ./
COPY --from=ts-compiler /usr/index/apps/resize/ecosystem.config.js ./
RUN addgroup -S app && adduser -S app -G app && chown -R app:app /usr/index
USER app

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--env", "development"]
