FROM node:20-alpine
WORKDIR /usr/index
COPY ../../package.json ../../pnpm-lock.yaml ../../pnpm-workspace.yaml ../../tsconfig.json ./
COPY ../../apps ./apps
COPY ../../libs ./libs
RUN corepack enable && pnpm install --frozen-lockfile
