import {
	ClientServiceItem,
	DashboardData,
	DashboardSummary,
	EventListResponse,
	ImageListResponse,
	ImageResizeRecommendationsResponse,
	LifecycleEventListResponse,
	TimeseriesPoint,
} from './telemetry-api';

export const clientServicesFixture: ClientServiceItem[] = [
	{
		id: 'svc-catalog',
		slug: 'catalog-api',
		name: 'Catalog API',
		description: '상품 이미지 업로드와 조회를 담당하는 백엔드 서비스',
		owner: 'commerce-team',
		status: 'ACTIVE',
		createdAt: '2026-07-01T00:00:00.000Z',
		updatedAt: '2026-07-01T00:00:00.000Z',
		keyCount: 2,
		activeKeyCount: 1,
		subscriptionCount: 2,
		activeSubscriptionCount: 1,
		keys: [
			{
				id: 'key-catalog-active',
				clientServiceId: 'svc-catalog',
				name: 'local backend key',
				keyPrefix: 'cat123',
				scopes: { telemetry: 'write' },
				createdAt: '2026-07-01T00:10:00.000Z',
			},
			{
				id: 'key-catalog-revoked',
				clientServiceId: 'svc-catalog',
				name: 'old key',
				keyPrefix: 'old123',
				revokedAt: '2026-07-01T01:00:00.000Z',
				createdAt: '2026-07-01T00:05:00.000Z',
			},
		],
		lifecycleSubscriptions: [
			{
				id: 'sub-catalog-upload-completed',
				clientServiceId: 'svc-catalog',
				eventType: 'image.upload.completed',
				consumerGroup: 'catalog-image-consumer',
				isEnabled: true,
				description: '상품 서비스가 업로드 완료 이벤트를 소비합니다.',
				createdAt: '2026-07-01T00:15:00.000Z',
				updatedAt: '2026-07-01T00:15:00.000Z',
			},
			{
				id: 'sub-catalog-upload-failed',
				clientServiceId: 'svc-catalog',
				eventType: 'image.upload.failed',
				consumerGroup: 'catalog-image-failure-consumer',
				isEnabled: false,
				description: '실패 이벤트 임시 소비 설정',
				createdAt: '2026-07-01T00:20:00.000Z',
				updatedAt: '2026-07-01T00:25:00.000Z',
			},
		],
		imageResizePolicy: {
			id: 'resize-policy-catalog',
			clientServiceId: 'svc-catalog',
			mode: 'PRE_GENERATE',
			createdAt: '2026-07-01T00:30:00.000Z',
			updatedAt: '2026-07-01T00:35:00.000Z',
			variants: [
				{
					id: 'resize-variant-catalog-thumb',
					policyId: 'resize-policy-catalog',
					width: 400,
					height: 400,
					format: 'webp',
					isEnabled: true,
					description: '상품 목록 썸네일',
					createdAt: '2026-07-01T00:31:00.000Z',
					updatedAt: '2026-07-01T00:31:00.000Z',
				},
				{
					id: 'resize-variant-catalog-card',
					policyId: 'resize-policy-catalog',
					width: 800,
					height: 600,
					format: 'jpeg',
					isEnabled: false,
					description: '카드 이미지 후보',
					createdAt: '2026-07-01T00:32:00.000Z',
					updatedAt: '2026-07-01T00:36:00.000Z',
				},
			],
		},
	},
	{
		id: 'svc-admin',
		slug: 'admin-api',
		name: 'Admin API',
		owner: 'platform-team',
		status: 'DISABLED',
		createdAt: '2026-07-01T03:00:00.000Z',
		updatedAt: '2026-07-01T04:00:00.000Z',
		keyCount: 0,
		activeKeyCount: 0,
		subscriptionCount: 0,
		activeSubscriptionCount: 0,
		keys: [],
		lifecycleSubscriptions: [],
		imageResizePolicy: {
			id: 'resize-policy-admin',
			clientServiceId: 'svc-admin',
			mode: 'ON_DEMAND',
			variants: [],
			createdAt: '2026-07-01T04:00:00.000Z',
			updatedAt: '2026-07-01T04:00:00.000Z',
		},
	},
];

export const dashboardSummaryFixture: DashboardSummary = {
	range: {
		from: '2026-07-01T00:00:00.000Z',
		to: '2026-07-02T00:00:00.000Z',
	},
	totalEvents: 127,
	totalReads: 100,
	totalUploads: 5,
	totalResizes: 20,
	cacheHitRate: 0.8,
	cacheMissRate: 0.2,
	failureRate: 2 / 127,
	avgDurationMs: 38.4,
	p95DurationMs: 182.2,
	totalInputBytes: 1_024_000,
	totalOutputBytes: 684_000,
};

export const dashboardTimeseriesFixture: TimeseriesPoint[] = [
	{
		bucketStart: '2026-07-01T00:00:00.000Z',
		totalEvents: 22,
		cacheHits: 14,
		cacheMisses: 5,
		cacheHitRate: 14 / 19,
		resizeCompleted: 3,
		uploadCompleted: 1,
		failures: 0,
		avgDurationMs: 22.1,
		p95DurationMs: 91.4,
	},
	{
		bucketStart: '2026-07-01T06:00:00.000Z',
		totalEvents: 39,
		cacheHits: 27,
		cacheMisses: 8,
		cacheHitRate: 27 / 35,
		resizeCompleted: 7,
		uploadCompleted: 2,
		failures: 1,
		avgDurationMs: 44.7,
		p95DurationMs: 166.8,
	},
	{
		bucketStart: '2026-07-01T12:00:00.000Z',
		totalEvents: 66,
		cacheHits: 39,
		cacheMisses: 7,
		cacheHitRate: 39 / 46,
		resizeCompleted: 10,
		uploadCompleted: 2,
		failures: 1,
		avgDurationMs: 48.5,
		p95DurationMs: 182.2,
	},
];

export const eventListFixture: EventListResponse = {
	items: [
		{
			eventId: 'evt-resize-failed-1',
			eventType: 'image.resize.failed',
			occurredAt: '2026-07-01T12:31:00.000Z',
			sourceApp: 'resize',
			status: 'failed',
			clientServiceId: 'svc-catalog',
			clientServiceSlug: 'catalog-api',
			path: 'products/main',
			name: 'broken.png',
			imageKey: 'products/main/broken.png',
			width: 1280,
			height: 720,
			requestId: 'req-resize-900',
			errorCode: 'SHARP_INPUT_INVALID',
			errorMessage: '이미지 디코딩에 실패했습니다.',
			rawPayload: { reason: 'invalid-image' },
		},
		{
			eventId: 'evt-cache-hit-1',
			eventType: 'image.cache.hit',
			occurredAt: '2026-07-01T12:20:00.000Z',
			sourceApp: 'cache',
			status: 'success',
			clientServiceId: 'svc-catalog',
			clientServiceSlug: 'catalog-api',
			path: 'products/main',
			name: 'hero.png',
			imageKey: 'products/main/hero.png',
			width: 640,
			durationMs: 2,
			outputBytes: 18_400,
			requestId: 'req-cache-101',
			rawPayload: { cacheKey: 'products/main_640/xhero.png' },
		},
		{
			eventId: 'evt-upload-1',
			eventType: 'image.upload.completed',
			occurredAt: '2026-07-01T11:00:00.000Z',
			sourceApp: 'storage',
			status: 'success',
			clientServiceId: 'svc-admin',
			clientServiceSlug: 'admin-api',
			path: 'products/main',
			name: 'hero.png',
			imageKey: 'products/main/hero.png',
			durationMs: 12.5,
			inputBytes: 42_000,
			outputBytes: 30_000,
			requestId: 'req-upload-42',
			rawPayload: { format: 'png' },
		},
	],
	nextCursor: 'cursor-next-page',
};

export const lifecycleEventListFixture: LifecycleEventListResponse = {
	items: [
		{
			eventId: 'life-upload-failed-1',
			eventType: 'image.upload.failed',
			occurredAt: '2026-07-01T13:00:00.000Z',
			receivedAt: '2026-07-01T13:00:01.000Z',
			sourceApp: 'storage',
			environment: 'production',
			status: 'failed',
			clientServiceId: 'svc-catalog',
			clientServiceSlug: 'catalog-api',
			requestId: 'req-upload-failed-777',
			traceId: 'trace-upload-failed-777',
			path: 'products/main',
			name: 'broken.png',
			imageKey: 'products/main/broken.png',
			format: 'unknown',
			inputBytes: 128,
			durationMs: 8.2,
			errorCode: 'BadRequestException',
			errorMessage: '지원하지 않는 이미지 형식입니다.',
			rawPayload: { mimeType: 'application/octet-stream' },
		},
		{
			eventId: 'life-upload-completed-1',
			eventType: 'image.upload.completed',
			occurredAt: '2026-07-01T12:42:00.000Z',
			receivedAt: '2026-07-01T12:42:01.000Z',
			sourceApp: 'storage',
			environment: 'production',
			status: 'success',
			clientServiceId: 'svc-catalog',
			clientServiceSlug: 'catalog-api',
			requestId: 'req-upload-900',
			traceId: 'trace-upload-900',
			imageId: 200,
			path: 'products/main',
			name: 'hero.png',
			imageKey: 'products/main/hero.png',
			format: 'png',
			inputBytes: 42_000,
			outputBytes: 30_000,
			durationMs: 12.5,
			rawPayload: { contentType: 'image/png' },
		},
		{
			eventId: 'life-upload-completed-2',
			eventType: 'image.upload.completed',
			occurredAt: '2026-07-01T10:00:00.000Z',
			receivedAt: '2026-07-01T10:00:01.000Z',
			sourceApp: 'storage',
			environment: 'production',
			status: 'success',
			clientServiceId: 'svc-admin',
			clientServiceSlug: 'admin-api',
			requestId: 'req-upload-admin-1',
			imageId: 201,
			path: 'products/thumb',
			name: 'card.jpg',
			imageKey: 'products/thumb/card.jpg',
			format: 'jpg',
			inputBytes: 24_000,
			outputBytes: 18_000,
			durationMs: 10.1,
			rawPayload: { contentType: 'image/jpeg' },
		},
	],
	nextCursor: 'life-cursor-next-page',
};

export const imageListFixture: ImageListResponse = {
	items: [
		{
			imageKey: 'products/main/hero.png',
			imageId: 100,
			path: 'products/main',
			name: 'hero.png',
			format: 'png',
			totalReads: 88,
			totalResizes: 14,
			totalCacheHits: 72,
			totalCacheMisses: 16,
			cacheHitRate: 72 / 88,
			totalFailures: 1,
			avgDurationMs: 32.2,
			p95DurationMs: 140.5,
			lastSeenAt: '2026-07-01T12:20:00.000Z',
		},
		{
			imageKey: 'products/thumb/card.jpg',
			imageId: 101,
			path: 'products/thumb',
			name: 'card.jpg',
			format: 'jpg',
			totalReads: 31,
			totalResizes: 5,
			totalCacheHits: 22,
			totalCacheMisses: 9,
			cacheHitRate: 22 / 31,
			totalFailures: 0,
			avgDurationMs: 18.4,
			p95DurationMs: 64.1,
			lastSeenAt: '2026-07-01T10:08:00.000Z',
		},
	],
	nextCursor: undefined,
};

export const imageResizeRecommendationsFixture: ImageResizeRecommendationsResponse =
	{
		threshold: {
			minRequests: 3,
		},
		items: [
			{
				recommendationKey: 'svc-catalog:400x400:webp',
				clientServiceId: 'svc-catalog',
				clientServiceSlug: 'catalog-api',
				width: 400,
				height: 400,
				format: 'webp',
				requestCount: 12,
				imageCount: 4,
				avgDurationMs: 30,
				p95DurationMs: 52,
				estimatedSavedResizeMs: 360,
				totalInputBytes: 960_000,
				totalOutputBytes: 240_000,
				lastRequestedAt: '2026-07-01T12:35:00.000Z',
				sampleImageKeys: [
					'products/main/hero.png',
					'products/thumb/card.jpg',
					'products/list/item.png',
				],
				recommended: true,
			},
			{
				recommendationKey: 'svc-admin:320x240:jpeg',
				clientServiceId: 'svc-admin',
				clientServiceSlug: 'admin-api',
				width: 320,
				height: 240,
				format: 'jpeg',
				requestCount: 1,
				imageCount: 1,
				avgDurationMs: 18.4,
				p95DurationMs: 18.4,
				estimatedSavedResizeMs: 18,
				totalInputBytes: 42_000,
				totalOutputBytes: 12_000,
				lastRequestedAt: '2026-07-01T10:08:00.000Z',
				sampleImageKeys: ['products/thumb/card.jpg'],
				recommended: false,
			},
		],
	};

export const dashboardDataFixture: DashboardData = {
	summary: dashboardSummaryFixture,
	timeseries: dashboardTimeseriesFixture,
	topImages: imageListFixture.items,
};
